# Generated by Django 5.2 on 2025-07-30 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "account_and_entitys",
            "0002_alter_xx_pivotfund_account_alter_xx_pivotfund_entity",
        ),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[], 
            state_operations=[]
        )
    ]
