# Generated by Django 5.2 on 2025-09-04 21:40

from django.db import migrations, models
from django.db.utils import DatabaseError


class SafeAlterField(migrations.AlterField):
    """Custom AlterField operation that handles Oracle field modification errors gracefully"""
    
    def database_forwards(self, app_label, schema_editor, from_state, to_state):
        try:
            super().database_forwards(app_label, schema_editor, from_state, to_state)
        except DatabaseError as e:
            error_str = str(e)
            # Oracle: invalid modification of columns
            # Oracle: inconsistent datatypes
            # Oracle: column to be modified must be empty to change datatype
            if any(code in error_str for code in ["ORA-22859", "ORA-00932", "ORA-01439"]):
                print(f"Skipping field alteration - Oracle datatype issue: {self.model_name}.{self.name}")
                return
            else:
                raise


class Migration(migrations.Migration):

    dependencies = [
        ('account_and_entitys', '0007_oracle_safe_transform'),
    ]

    operations = [
        SafeAlterField(
            model_name='xx_account',
            name='account',
            field=models.CharField(max_length=50, unique=True),
        ),
        SafeAlterField(
            model_name='xx_account_entity_limit',
            name='account_id',
            field=models.CharField(max_length=50),
        ),
        SafeAlterField(
            model_name='xx_account_entity_limit',
            name='entity_id',
            field=models.CharField(max_length=50),
        ),
        SafeAlterField(
            model_name='xx_entity',
            name='entity',
            field=models.CharField(max_length=50, unique=True),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='account',
            field=models.CharField(max_length=50),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='actual',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='encumbrance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='entity',
            field=models.CharField(max_length=50),
        ),
        SafeAlterField(
            model_name='xx_pivotfund',
            name='fund',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
